### ISSUE TITLE
Job running without Flask app context

### ISSUE THREAD

**Issue by timorthi** [rq/Flask-RQ2#50]
Hi, I'm trying to save to my db in one of my jobs, but I am getting the out of context error: `RuntimeError: No application found. Either work inside a view function or push an application context.`  

Here's a simple example that tests for the app context.

```
$ export FLASK_APP=app.py
$ flask run
```

```
# app.py

from flask import Flask, has_app_context
from flask_rq2 import RQ

app = Flask(__name__)
app.config['RQ_REDIS_URL'] = 'redis://127.0.0.1:6379/0'

rq = RQ(app)


@rq.job
def add(x, y):
    print(has_app_context()) # False
    return x + y


@app.route('/')
def index():
    add.queue(1, 3)
    return 'hello world!'
```

I can get around this by using `ScriptInfo().load_app()`, or with a delayed app instance import, but that's not ideal. 

```
from flask.cli import ScriptInfo

@rq.job
def add(x, y):
    with ScriptInfo().load_app().app_context():
        print(has_app_context()) # True
    return x + y
```

```
@rq.job
def add(x, y):
    from module_where_app_is_created import app
    with app.app_context():
        print(has_app_context()) # True
    return x + y
```

**Comment by timorthi** [comment]
Here's a much simpler example that gave me the same problem. I tested `flask.g` which is bound to the application context. 

```
$ export FLASK_APP=app.py
$ flask run
```

```
# app.py

from flask import Flask, g
from flask_rq2 import RQ

app = Flask(__name__)
app.config['SECRET_KEY'] = 'top_secret_string'
app.config['RQ_REDIS_URL'] = 'redis://127.0.0.1:6379/0'

rq = RQ(app)


@rq.job
def add(x, y):
    print(g) # RuntimeError: Working outside of application context.
    return x + y


@app.route('/')
def index():
    add.queue(1, 3)
    return 'hello world!'
```

Oddly enough, I can get around this by using `ScriptInfo().load_app()`. This hack also works in the original example I posted above:
```
# app.py

...

from flask.cli import ScriptInfo

@rq.job
def add(x, y):
    with ScriptInfo().load_app().app_context():
        print(g) # outputs <flask.g of 'app'>
    return x + y

...
```

**Comment by jezdez** [comment]
I tried your code and wasn't able to reproduce it. Are you using the latest version of flask-rq2? I changed a lot of how this works in https://github.com/rq/Flask-RQ2/commit/d4d5e526d0790d1968f34b10ec42a12ab6e944cd.

**Comment by jezdez** [comment]
See https://github.com/jezdez/rq2test for a quick test as well.

**Comment by timorthi** [comment]
Silly me... After looking at your test example I saw where I went wrong - I was starting my worker process using `rq worker` instead of `flask rq worker`. Using the latter solved the problem for me.  

It's my fault for overlooking the CLI support section in the docs, but do you think adding this to the Getting Started section would prevent similar confusion down the line?

**Comment by jezdez** [comment]
@timorthi AH, gotcha, that'd explain it. Thanks for checking :) I opened https://github.com/rq/Flask-RQ2/issues/52 to follow-up on this, a getting started guide is a great idea.

**Comment by gx303841541** [comment]
excuse me,  how can I use I special Redis address?  there seams no arg can handle this:  flask rq  worker --url  redis://:123@redis:6379/3
