### ISSUE TITLE
Reenable pyup.io

### ISSUE THREAD

**Issue by jezdez** [rq/Flask-RQ2#51]
Hi @nvie,

would you mind re-enabling [pyup.io](https://pyup.io/) again or give me enough permissions to be able to to it myself?

Thanks!

**Comment by nvie** [comment]
Hey @jezdez, I just made you an admin collab on this repo. Will that work for you? Feel free to add it.

**Comment by jezdez** [comment]
@nvie Doesn't seem to be enough, would you mind enabling it here? https://pyup.io/account/repos/add/

**Comment by nvie** [comment]
@jezdez I just added the repo. I’m not familiar with the service, but it seems to work. Does this work for you?

**Comment by jezdez** [comment]
Yep, thank you!
