### ISSUE TITLE
[help] How to get job by job_id in Flask-RQ2

### ISSUE THREAD

**Issue by ngxlua** [rq/Flask-RQ2#59]
I added a job, but I found that I have no way to get it through job_id. What should I do?

```
tasks.run.queue("test", 1234, a=1, b=2, job_id="test-job")
```

**Comment by ngxlua** [comment]
At the same time I also want to know how to get the return value of job, thanks

**Comment by florpor** [comment]
You can use your rq instance to get the job:
`rq.get_queue().fetch_job(job_id)`

The result is None as long as the job hasn't executed. Once it has you'll see your result
