### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by fcakyon** [rq/Flask-RQ2#95]
Hello, RQ is a well maintained project and I would like to use it my flask app but seeing last release is from 2 years ago, master ci is failing and there are lots of unanswered issues and prs, flask-rq2 project seems to deprecated. 

So my question is, is it better to create by own [rq](https://github.com/rq/rq) wrapper in my flask app instead of using [this project](https://github.com/rq/Flask-RQ2)?

**Comment by jezdez** [comment]
This project is still active.
